### ISSUE TITLE
Doesn't work with Wallet extension

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Conditional-Gateways#1]
If you limit a product to the Wallet gateway, the error message shows that there are no gateways available.

[Reported here](https://secure.helpscout.net/conversation/159098825/24914/?folderId=180499) and confirmed locally.

**Comment by pippinsplugins** [comment]
Would be nice to see this supported.

**Comment by mindctrl** [comment]
@ghost1227 you had a chance to look at this?

**Comment by pippinsplugins** [comment]
Ticket: https://secure.helpscout.net/conversation/159098825/24914/?folderId=180505

@ghost1227 We need this fixed pleased.
